// // Mocks generated by Mockito 5.4.5 from annotations
// // in numero_uno/test/widget_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i3;

// import 'package:mockito/mockito.dart' as _i1;
// import 'package:numero_uno/models/numerology_result.dart' as _i5;
// import 'package:numero_uno/models/user_data.dart' as _i4;
// import 'package:numero_uno/services/storage_service.dart' as _i2;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// /// A class which mocks [StorageService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockStorageService extends _i1.Mock implements _i2.StorageService {
//   MockStorageService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<void> saveUserInput(
//     _i4.UserData? userInput, {
//     String? userId,
//     bool? isGuest = true,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(
//               #saveUserInput,
//               [userInput],
//               {#userId: userId, #isGuest: isGuest},
//             ),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   List<_i4.UserData> getUserInputs() =>
//       (super.noSuchMethod(
//             Invocation.method(#getUserInputs, []),
//             returnValue: <_i4.UserData>[],
//           )
//           as List<_i4.UserData>);

//   @override
//   _i3.Future<void> saveNumerologyResult(
//     _i5.NumerologyResult? result, {
//     String? userId,
//     bool? isGuest = true,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(
//               #saveNumerologyResult,
//               [result],
//               {#userId: userId, #isGuest: isGuest},
//             ),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   List<_i5.NumerologyResult> getNumerologyResults() =>
//       (super.noSuchMethod(
//             Invocation.method(#getNumerologyResults, []),
//             returnValue: <_i5.NumerologyResult>[],
//           )
//           as List<_i5.NumerologyResult>);

//   @override
//   _i3.Future<_i5.NumerologyResult?> getNumerologyResultByUserId(
//     String? userId,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#getNumerologyResultByUserId, [userId]),
//             returnValue: _i3.Future<_i5.NumerologyResult?>.value(),
//           )
//           as _i3.Future<_i5.NumerologyResult?>);

//   @override
//   _i3.Future<_i5.NumerologyResult?> getNumerologyResultFromFirestoreByName(
//     String? name,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#getNumerologyResultFromFirestoreByName, [name]),
//             returnValue: _i3.Future<_i5.NumerologyResult?>.value(),
//           )
//           as _i3.Future<_i5.NumerologyResult?>);

//   @override
//   _i3.Future<void> saveNumerologyResultToFirestore(
//     _i5.NumerologyResult? result,
//     String? userId,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#saveNumerologyResultToFirestore, [
//               result,
//               userId,
//             ]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> saveNumerologyResultToFirestoreByName(
//     _i5.NumerologyResult? result,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#saveNumerologyResultToFirestoreByName, [result]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> clearAllData() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearAllData, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   Map<String, int> getStorageStats() =>
//       (super.noSuchMethod(
//             Invocation.method(#getStorageStats, []),
//             returnValue: <String, int>{},
//           )
//           as Map<String, int>);

//   @override
//   _i3.Future<void> close() =>
//       (super.noSuchMethod(
//             Invocation.method(#close, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);
// }
