name: numero_uno
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.21.2
  
  # Navigation
  go_router: ^16.0.0
  

  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  url_launcher: ^6.3.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  firebase_app_check: ^0.3.2+10
  web: ^1.1.1
  flutter_svg: ^2.2.0
  pwa_install: ^0.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.4
  
  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  

flutter_launcher_icons:
  image_path: "assets/app_logo.png"
  android:
    generate: true  # can specify file name here e.g. "ic_launcher"
  ios: 
    true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/app_logo.png"

  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
