// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmqSELedcPH1MGfpT6xzlRkTj5gLQXa0',
    appId: '1:212454234271:web:8f55698fd5c95815966aaa',
    messagingSenderId: '212454234271',
    projectId: 'numerouno-dca40',
    authDomain: 'numerouno-dca40.firebaseapp.com',
    storageBucket: 'numerouno-dca40.firebasestorage.app',
    measurementId: 'G-W1P9MM1HJ7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfp5ICUs8VgPi55NOy3Iz89Sq2x_A4-0',
    appId: '1:212454234271:ios:3aa16e51e1aa49d6966aaa',
    messagingSenderId: '212454234271',
    projectId: 'numerouno-dca40',
    storageBucket: 'numerouno-dca40.firebasestorage.app',
    iosClientId: '212454234271-b82s4kgou87srdtsudm9rdo80mqmmp9v.apps.googleusercontent.com',
    iosBundleId: 'awes0m.github.io.numeroUno',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9saV3aNJfrKZ_n-8Noz4hGbyAusvTJac',
    appId: '1:212454234271:android:ddee272bf2252fb5966aaa',
    messagingSenderId: '212454234271',
    projectId: 'numerouno-dca40',
    storageBucket: 'numerouno-dca40.firebasestorage.app',
  );

}